{
    "Computer":  "HYPERVISOR",
    "Events":  [
                   {
                       "TimeCreated":  "\/Date(1761527592022)\/",
                       "Source":  "Microsoft-Windows-WindowsUpdateClient",
                       "LogName":  "Microsoft-Windows-WindowsUpdateClient/Operational",
                       "Level":  "Error",
                       "Message":  "Windows Update failed to check for updates with error 0x8024402F.",
                       "Id":  25,
                       "ErrorCode":  "0x8024402F",
                       "UpdateTitle":  null,
                       "EventRecordID":  26240
                   },
                   {
                       "TimeCreated":  "\/Date(1761521404960)\/",
                       "Source":  "Microsoft-Windows-TaskScheduler",
                       "LogName":  "Microsoft-Windows-TaskScheduler/Operational",
                       "Level":  "Error",
                       "Message":  "Task Scheduler failed to start instance \"{a5531035-d671-4c2f-afa4-e14d665b0256}\" of \"\\Microsoft\\Windows\\DiskFootprint\\StorageSense\"  task for user \"NT AUTHORITY\\SYSTEM\" . Additional Data: Error Value: 2147746132.",
                       "Id":  103,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  161660
                   },
                   {
                       "TimeCreated":  "\/Date(1761521404960)\/",
                       "Source":  "Microsoft-Windows-TaskScheduler",
                       "LogName":  "Microsoft-Windows-TaskScheduler/Operational",
                       "Level":  "Error",
                       "Message":  "Task Scheduler failed to complete task \"\\Microsoft\\Windows\\DiskFootprint\\StorageSense\" , instance \"{a5531035-d671-4c2f-afa4-e14d665b0256}\" , action \"StorageUsage State Reporter Task Handler\" . Additional Data: Error Value: 2147746132.",
                       "Id":  202,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  161659
                   },
                   {
                       "TimeCreated":  "\/Date(1761519846710)\/",
                       "Source":  "VSS",
                       "LogName":  "Application",
                       "Level":  "Error",
                       "Message":  "Volume Shadow Copy Service error: Unexpected error DeviceIoControl(\\\\?\\GLOBALROOT\\Device\\HarddiskVolumeShadowCopy137 - 00000000000003F0,0x0053c198,0000024CCE73E750,0,0000024CCE73B450,4096,[0]).  hr = 0x80070057, The parameter is incorrect.\r",
                       "Id":  12289,
                       "ErrorCode":  "0x0053c198",
                       "UpdateTitle":  null,
                       "EventRecordID":  77436
                   },
                   {
                       "TimeCreated":  "\/Date(1761513635196)\/",
                       "Source":  "Microsoft-Windows-TaskScheduler",
                       "LogName":  "Microsoft-Windows-TaskScheduler/Operational",
                       "Level":  "Error",
                       "Message":  "Task Scheduler failed to start \"\\Microsoft\\Windows\\UpdateOrchestrator\\USO_UxBroker\" task for user \"NT AUTHORITY\\SYSTEM\". Additional Data: Error Value: 2147942402.",
                       "Id":  101,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  161354
                   },
                   {
                       "TimeCreated":  "\/Date(1761513635195)\/",
                       "Source":  "Microsoft-Windows-TaskScheduler",
                       "LogName":  "Microsoft-Windows-TaskScheduler/Operational",
                       "Level":  "Error",
                       "Message":  "Task Scheduler failed to launch action \"%systemroot%\\system32\\MusNotification.exe\" in instance \"{5c57deaf-6fcc-403c-9175-52581515ca50}\" of task \"\\Microsoft\\Windows\\UpdateOrchestrator\\USO_UxBroker\". Additional Data: Error Value: 2147942402.",
                       "Id":  203,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  161353
                   },
                   {
                       "TimeCreated":  "\/Date(1761513311611)\/",
                       "Source":  "Schannel",
                       "LogName":  "System",
                       "Level":  "Error",
                       "Message":  "The certificate received from the remote server was issued by an untrusted certificate authority. Because of this, none of the data contained in the certificate can be validated. The TLS connection request has failed. The attached data contains the server certificate.\r",
                       "Id":  36882,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  313053
                   },
                   {
                       "TimeCreated":  "\/Date(1761484813569)\/",
                       "Source":  "Microsoft-Windows-TPM-WMI",
                       "LogName":  "System",
                       "Level":  "Error",
                       "Message":  "The Secure Boot update failed to update a Secure Boot variable with error Secure Boot is not enabled on this machine.. For more information, please see https://go.microsoft.com/fwlink/?linkid=2169931",
                       "Id":  1796,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  311223
                   }
               ],
    "LastPoll":  "10/26 18:18"
}