{
    "Computer":  "SERVER2019",
    "Events":  [
                   {
                       "TimeCreated":  "\/Date(1759920213781)\/",
                       "Source":  "LHWinService",
                       "LogName":  "Application",
                       "Level":  "Error",
                       "Message":  "  There may be a configuration problem: please check the logs.",
                       "Id":  100,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  256223
                   },
                   {
                       "TimeCreated":  "\/Date(1759911687720)\/",
                       "Source":  "Microsoft-Windows-WindowsUpdateClient",
                       "LogName":  "System",
                       "Level":  "Error",
                       "Message":  "Installation Failure: Windows failed to install the following update with error 0x80073701: 2025-09 Cumulative Update for Windows Server 2019 (1809) for x64-based Systems (KB5065428).",
                       "Id":  20,
                       "ErrorCode":  "0x80073701",
                       "UpdateTitle":  "2025-09 Cumulative Update for Windows Server 2019 (1809) for x64-based Systems (KB5065428)",
                       "EventRecordID":  2902807
                   },
                   {
                       "TimeCreated":  "\/Date(1759896397791)\/",
                       "Source":  "VSS",
                       "LogName":  "Application",
                       "Level":  "Error",
                       "Message":  "Volume Shadow Copy Service error: Unexpected error querying for the IVssWriterCallback interface.  hr = 0x80070005, Access is denied.\r",
                       "Id":  8194,
                       "ErrorCode":  "0x80070005",
                       "UpdateTitle":  null,
                       "EventRecordID":  256004
                   },
                   {
                       "TimeCreated":  "\/Date(1759837307206)\/",
                       "Source":  "Service Control Manager",
                       "LogName":  "System",
                       "Level":  "Error",
                       "Message":  "The Service Control Manager tried to take a corrective action (Restart the service) after the unexpected termination of the Vyne Sync service, but this action failed with the following error: \r",
                       "Id":  7032,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  2900349
                   },
                   {
                       "TimeCreated":  "\/Date(1759835507201)\/",
                       "Source":  "Service Control Manager",
                       "LogName":  "System",
                       "Level":  "Error",
                       "Message":  "The Vyne Sync service terminated unexpectedly.  It has done this 1 time(s).  The following corrective action will be taken in 1800000 milliseconds: Restart the service.",
                       "Id":  7031,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  2900287
                   },
                   {
                       "TimeCreated":  "\/Date(1759835507130)\/",
                       "Source":  "Service Control Manager",
                       "LogName":  "System",
                       "Level":  "Error",
                       "Message":  "The Vyne Sync Watchdog service terminated unexpectedly.  It has done this 1 time(s).",
                       "Id":  7034,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  2900285
                   }
               ],
    "LastPoll":  "10/08 04:11"
}