{
    "Computer":  "SERVER2019",
    "Events":  [
                   {
                       "TimeCreated":  "\/Date(1758753810641)\/",
                       "Source":  "LHWinService",
                       "LogName":  "Application",
                       "Level":  "Error",
                       "Message":  "  There may be a configuration problem: please check the logs.",
                       "Id":  100,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  246705
                   },
                   {
                       "TimeCreated":  "\/Date(1758745298705)\/",
                       "Source":  "VSS",
                       "LogName":  "Application",
                       "Level":  "Error",
                       "Message":  "Volume Shadow Copy Service error: Unexpected error querying for the IVssWriterCallback interface.  hr = 0x80070005, Access is denied.\r",
                       "Id":  8194,
                       "ErrorCode":  "0x80070005",
                       "UpdateTitle":  null,
                       "EventRecordID":  246636
                   },
                   {
                       "TimeCreated":  "\/Date(1758701624770)\/",
                       "Source":  "Microsoft-Windows-WindowsUpdateClient",
                       "LogName":  "System",
                       "Level":  "Error",
                       "Message":  "Installation Failure: Windows failed to install the following update with error 0x80073701: 2025-09 Cumulative Update for Windows Server 2019 (1809) for x64-based Systems (KB5065428).",
                       "Id":  20,
                       "ErrorCode":  "0x80073701",
                       "UpdateTitle":  "2025-09 Cumulative Update for Windows Server 2019 (1809) for x64-based Systems (KB5065428)",
                       "EventRecordID":  2858418
                   },
                   {
                       "TimeCreated":  "\/Date(1758700439794)\/",
                       "Source":  "NexHealthSync",
                       "LogName":  "Application",
                       "Level":  "Error",
                       "Message":  "The instance\u0027s SvcRun() method failed \r",
                       "Id":  3,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  246230
                   },
                   {
                       "TimeCreated":  "\/Date(1758700439794)\/",
                       "Source":  "NexHealthSync",
                       "LogName":  "Application",
                       "Level":  "Error",
                       "Message":  "SetServiceStatus failed setting STOPPED status Error 6 - The handle is invalid.",
                       "Id":  242,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  246231
                   },
                   {
                       "TimeCreated":  "\/Date(1758674838801)\/",
                       "Source":  "Service Control Manager",
                       "LogName":  "System",
                       "Level":  "Error",
                       "Message":  "The Service Control Manager tried to take a corrective action (Restart the service) after the unexpected termination of the Practice Data Sync service, but this action failed with the following error: \r",
                       "Id":  7032,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  2857406
                   },
                   {
                       "TimeCreated":  "\/Date(1758674778800)\/",
                       "Source":  "Service Control Manager",
                       "LogName":  "System",
                       "Level":  "Error",
                       "Message":  "The Practice Data Sync service terminated unexpectedly.  It has done this 1 time(s).  The following corrective action will be taken in 60000 milliseconds: Restart the service.",
                       "Id":  7031,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  2857402
                   }
               ],
    "LastPoll":  "09/24 15:56"
}